# database.yaml

development:
  adapter: postgresql
  database: rails_dev
  username: rails
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: rails_test
  username: rails
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: rails_prod
  username: rails
  pool: 5
  timeout: 5000
